# ************ CCC Modification ************ 
CCC_OPTS_DEF =
ifneq ($(CCC_OPTS),)
CCC_OPTS_DEF=$(CCC_OPTS)
endif
# ******************************************

# Declarations
COMPILER = pathcc
MISC_OPTS = -lm

# Actions
all:		
	$(COMPILER) $(CCC_OPTS_DEF) $(MISC_OPTS) *.c

clean:
	rm -f a.out *.o *.a *.s *.i *.I
       