#!/bin/bash

# Copyright (C) 2004-2009 by Grigori Fursin
#
# http://fursin.net/research
# 
# UNIDAPT Group
# http://unidapt.org

ICI_PASS_DIR=ici-passes

################################################################################
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] ; then
 echo "Usage:"
 echo " ccc-ici-passes-record <Output file> <Compiler extension> <Compiler flags>"
 exit 1
fi

CUR_DIR=$PWD

if [ ! -d "$CCC_ICI_PASSES_USE_TEST_DIR" ] ; then
 echo ""
 echo "Directory $CCC_ICI_PASSES_USE_TEST_DIR doesn't exist!"
 exit
fi

cd $CCC_ICI_PASSES_USE_TEST_DIR

rm -f Makefile
cp -f Makefile.$2 Makefile

rm -f $CCC_ICI_PASSES_FN.*$CCC_ICI_PASSES_EXT
export ICI_USE=1
export ICI_PLUGIN=$CCC_ICI_PASSES_RECORD_PLUGIN

export CCC_OPTS=$3
make

cp -f $CCC_ICI_PASSES_FN.$CCC_ICI_PASSES_USE_FUNCTION$CCC_ICI_PASSES_EXT $CUR_DIR/$1

cd $CUR_DIR
