#!/bin/bash

# Copyright (C) 2004-2009 by Grigori Fursin
#
# http://fursin.net/research
# 
# UNIDAPT Group
# http://unidapt.org

UUID=uuidgen
if [ ! -z $CCC_UUID ] ; then
 UUID=$CCC_UUID
fi

$UUID | while read line;
do
if [ ! -z $line ] ; then
 var1=""
 var2=""
 
 j=0
 for i in `seq 0 35`;
 do
  var=${line:$i:1}
  if [ $var != "-" ] ; then
   let j=j+1
   if [ "$j" -lt "9" ] ; then
    var1=$var1$var
   elif [ "$j" -lt "15" ] ; then
    var2=$var2$var
   fi
  fi
 done

 let xvar1=0x$var1
 let xvar2=0x$var2
 
 echo $xvar1
 echo $xvar2
fi
done
