#!/bin/bash

# Copyright (C) 2004-2007 by Grigori Fursin
#
# http://fursin.net/research
# 
# UNIDAPT Group
# http://unidapt.org

# Set database variables
if [ -f "ccc--select-db.sh" ] ; then
 . ./ccc--select-db.sh
fi

export RUN_ID=$1

php $CCC_PLUGINS/plugins/copy2ctdb_run.php
