#!/bin/bash

# Copyright (C) 2004-2007 by Grigori Fursin
#
# http://fursin.net/research
# 
# UNIDAPT Group
# http://unidapt.org

STAT_FILE=Stats/_stats__all_platforms

# Set database variables
if [ -f "ccc--select-db.sh" ] ; then
 . ./ccc--select-db.sh
fi

# Delete previous statistic (some files are appended)
rm -rf ${STAT_FILE}*

# Run script to generate statistics
export CCC_STATS=$STAT_FILE

php $CCC_PLUGINS/plugins/get_all_platforms.php
