#!/bin/bash

# Copyright (C) 2004-2010 by Grigori Fursin
#
# http://fursin.net/research
# 
# UNIDAPT Group
# http://unidapt.org

STAT_FILE=Stats/_stats__all_global_speedups
STAT_FILE1=Stats/_stats__global_speedups
STAT_FILE_S=${STAT_FILE}._SUMMARY.txt

# Set database variables
if [ -f "ccc--select-db.sh" ] ; then
 . ./ccc--select-db.sh
fi

# Delete previous statistic (some files are appended)
rm -rf ${STAT_FILE}.*

export PLAT_ID=708176059411291686
#110787249241129258  AMD Opteron 2218
#708176059411291686  Intel Xeon EM64T

export CMPLR_ID=329504539516446542
#329504539516446542  gcc 4.4.0

export ENV_ID=198828472341129319
#198828472341129319  Debian Sid Linux v1.1

#retrieve opt cases only when execution time > TIME_THRESHOLD
export TIME_THRESHOLD=0.3

#retrieve opt cases only with specific notes
export NOTES=

#retrieve opt cases only when profile info is !=""
export PG_USE=1

#retrieve opt cases only when execution output is correct (or not if =0)
export OUTPUT_CORRECT=1

#sort optimization case by speedup (0 - ex. time, 1 - code size, 2 - comp time)
export SORT=012

#check user or total execution time
#export RUN_TIME=RUN_TIME_USER
export RUN_TIME=RUN_TIME

#Produce frontier
#export DIM=01 (2D frontier)
#export DIM=02 (2D frontier)
#export DIM=12 (2D frontier)
#export DIM=012 (3D frontier)
export DIM=012

#Cut cases during frontier (select cases when speedup 0,1 or 2 is more than some threshold)
#export CUT=0,0,1.2
#export CUT=1,1,1
export CUT=0,0,0

export CCC_FILE_TMP=tmp

exec 9< list-progs.dat
while read <&9 str1 str2 str3 str4 
do 
   echo ""
   echo Processing $str2 ...
   echo ""
   export PROG_ID=$str1

   export DS_NUM=1

   export CCC_STATS=${STAT_FILE}
   get-global-speedups

   exec 8< $STAT_FILE1.sort_by_${SORT}.csv
   read <&8 speedup
   exec 8>&-

   echo $str2"," $speedup >> ${STAT_FILE_S}

   cp $STAT_FILE1.sort_by_${SORT}.csv $STAT_FILE.$str2.sort_by_${SORT}.csv
   cp $STAT_FILE1.csv $STAT_FILE.$str2.csv
   cp $STAT_FILE1.frontier.csv $STAT_FILE.$str2.frontier.csv
   cp $STAT_FILE1.txt $STAT_FILE.$str2.txt

   echo "" >> $STAT_FILE.$str2.txt
   echo "All speedups (averaged while RUN_ID, COMPILE_ID relates to the last optimization case):" >> $STAT_FILE.$str2.txt
   echo "" >> $STAT_FILE.$str2.txt
   cat $CCC_FILE_TMP >> $STAT_FILE.$str2.txt
done
exec 9>&-
