#!/bin/bash

# Copyright (C) 2004-2010 by Grigori Fursin
#
# http://fursin.net/research
# 
# UNIDAPT Group
# http://unidapt.org

rm -rf fig_bar_graph.eps

gnuplot "$CCC_PLUGINS/plugins/plot_bar_graph.plot"
